.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinsn_qt test_bitcoinsn_qt
clean: FORCE
	$(MAKE) -C .. bitcoinsn_qt_clean test_bitcoinsn_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinsn_qt_check
bitcoinsn-qt bitcoinsn-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinsn_qt
